//go:build ignore

// Command gen_keysyms builds keysyms.go from X11 keysym header files.
//
// Usage (from package directory or via go:generate):
//
//	go run ./gen_keysyms.go -o keysyms.go
//
// By default headers are read from $X11_INCLUDE/X11 or /usr/include/X11:
//
//	keysymdef.h  XF86keysym.h  Sunkeysym.h  DECkeysym.h  HPkeysym.h  ap_keysym.h
//
// Regenerating requires those headers (e.g. package libx11-dev / libX11-devel).
// The generated keysyms.go is committed so builds and tests work without them.
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var headerFiles = []string{
	"keysymdef.h",
	"XF86keysym.h",
	"Sunkeysym.h",
	"DECkeysym.h",
	"HPkeysym.h",
	"ap_keysym.h",
}

// #define XK_Alt_L 0xffe9
// #define XF86XK_AudioMute 0x1008FF12 /* comment */
var defineRe = regexp.MustCompile(`^#define\s+(XK_|XF86XK_|SunXK_|DXK_|hpXK_|osfXK_|apXK_)([A-Za-z0-9_]+)\s+(0x[0-9A-Fa-f]+|\d+)\b`)

func main() {
	outPath := flag.String("o", "keysyms.go", "output Go file")
	includeDir := flag.String("include", "", "X11 include directory containing keysym headers (default: $X11_INCLUDE/X11 or /usr/include/X11)")
	flag.Parse()

	dir := *includeDir
	if dir == "" {
		if x := os.Getenv("X11_INCLUDE"); x != "" {
			dir = filepath.Join(x, "X11")
		} else {
			dir = "/usr/include/X11"
		}
	}

	table := make(map[string]uint32)
	var sources []string
	for _, name := range headerFiles {
		path := filepath.Join(dir, name)
		n, err := parseHeader(path, table)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			fmt.Fprintf(os.Stderr, "parse %s: %v\n", path, err)
			os.Exit(1)
		}
		if n > 0 {
			sources = append(sources, name)
			fmt.Fprintf(os.Stderr, "parsed %s: %d defines\n", path, n)
		}
	}
	if len(table) == 0 {
		fmt.Fprintf(os.Stderr, "no keysyms found under %s (install libx11 headers or pass -include)\n", dir)
		os.Exit(1)
	}

	if err := writeKeysyms(*outPath, table, sources, dir); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d names)\n", *outPath, len(table))
}

func parseHeader(path string, table map[string]uint32) (int, error) {
	f, err := os.Open(path)
	if err != nil {
		return 0, err
	}
	defer f.Close()

	n := 0
	sc := bufio.NewScanner(f)
	// Some lines can be long; default is fine for keysym headers.
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		m := defineRe.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		prefix, name, valStr := m[1], m[2], m[3]
		v, err := strconv.ParseUint(valStr, 0, 32)
		if err != nil {
			return n, fmt.Errorf("%s: parse value %q: %w", name, valStr, err)
		}
		val := uint32(v)

		// Bare name (Alt_L, AudioMute) — matches XKB_KEY_* after strip.
		add(table, name, val)
		// XF86 headers are often referenced as XF86AudioMute as well.
		if prefix == "XF86XK_" {
			add(table, "XF86"+name, val)
		}
		n++
	}
	return n, sc.Err()
}

func add(table map[string]uint32, name string, val uint32) {
	if prev, ok := table[name]; ok && prev != val {
		// Prefer first definition (canonical) when headers disagree.
		return
	}
	table[name] = val
}

func writeKeysyms(path string, table map[string]uint32, sources []string, dir string) error {
	names := make([]string, 0, len(table))
	for n := range table {
		names = append(names, n)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./gen_keysyms.go; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate (from repo root):\n")
	b.WriteString("//   go generate ./internal/xdo\n")
	b.WriteString("// or (from this package directory):\n")
	b.WriteString("//   go run ./gen_keysyms.go -o keysyms.go\n")
	b.WriteString("//\n")
	b.WriteString("// Requires X11 keysym headers (default include dir: /usr/include/X11).\n")
	b.WriteString("// Override with -include or $X11_INCLUDE.\n")
	b.WriteString("// Sources: ")
	b.WriteString(strings.Join(sources, ", "))
	b.WriteString(" (from ")
	b.WriteString(dir)
	b.WriteString(")\n\n")
	b.WriteString("package xdo\n\n")
	b.WriteString("// keysyms maps X11/xkb-style keysym names (without XK_/XKB_KEY_ prefix) to X keysym values.\n")
	b.WriteString("var keysyms = map[string]uint32{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: 0x%x,\n", name, table[name])
	}
	b.WriteString("}\n")

	return os.WriteFile(path, b.Bytes(), 0o644)
}
